language: generic
sudo: required
services:
    - docker 

before_install:
    - docker build -t sachinchandy/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sachinchandy/docker-react npm run test -- --coverage
